#!/usr/bin/env python3
"""Rebuild DoD_Roots.pem from the source bundles, and prove the result.

    ./tools/refresh_roots.py --check        is the committed bundle still right?
    ./tools/refresh_roots.py --write        rebuild it and the manifest
    ./tools/refresh_roots.py --verify-sources   check the sources are genuine

Why this exists
---------------
Sentinel ships a bundle of DoD trust anchors so that installing it never
requires the user to visit a website and download anything. That answers "how do
I get the certificates" but not the question that comes next: "how do I know
these are the current ones?"

Answering that offline needs two things this repository now carries: the signed
source bundles DoD publishes, and a manifest recording what the build produced.
This tool is the link between them.

    sources -> (self-signed filter) -> DoD_Roots.pem -> DoD_Roots.manifest

The filter is the security-relevant step. Each per-root `.p7b` from DoD contains
the root *and every certificate beneath it* -- 59 certificates in total across
the seven files -- so "take the first certificate" would install an issuing CA as
a root of trust, which is a materially larger trust surface than intended. Only
self-signed certificates are kept, and that is checked by verifying each
certificate's signature under its own public key rather than by comparing
subject and issuer strings.

`--verify-sources` checks the source files against the SHA-256 manifest that DoD
ships inside each bundle's `.sha256` file, which is a CMS object signed by a DoD
code-signing credential. That answers "are the files in this repository
unmodified?", which is a different and weaker question than "does the CMS
signature still validate?" -- see the note in `verify_sources`.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import sentinel_certs as certs  # noqa: E402

BUNDLE_NAME = "DoD_Roots.pem"
MANIFEST_NAME = certs.MANIFEST_NAME

# The source files, in the order the bundle is built. Order is part of the
# contract: the manifest records the bundle in this order, so changing it is a
# change to the release, not a cosmetic reordering.
#
# These are the per-root files rather than the combined ones on purpose. The
# combined `Certificates_PKCS7_v5.6_DoD.pem.p7b` carries DoD's own idea of which
# certificates belong, and this tool's job is to derive the roots independently
# and compare, not to take the publisher's word for which subset to trust.
SOURCES = (
    "certificates_pkcs7_v5_12_eca/certificates_pkcs7_v5_12_eca_ECA_Root_CA_4_der.p7b",
    "certificates_pkcs7_v5_12_eca/certificates_pkcs7_v5_12_eca_ECA_Root_CA_5_der.p7b",
    "Certificates_PKCS7_v5_17_WCF/Certificates_PKCS7_v5_17_WCF_DoD_WCF_Root_CA_1.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_5.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_4.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_3.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_2.der.p7b",
)

# Where DoD publishes the bundles, for the record in the commit message. Not
# fetched by this tool: a build that silently pulled from the network would make
# the release unreproducible, which is the opposite of what a manifest is for.
UPSTREAM = "https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/"

# Reproduced byte-for-byte on every build so that `--check` is a meaningful
# comparison. The certificates themselves are what matter; this only has to stay
# stable, and a reformat that changes no certificate should not read as a change
# to the trust store.
BUNDLE_HEADER = """\
# DoD root certificates (self-signed trust anchors only).
# Generated by tools/refresh_roots.py -- do not edit by hand.
# Regenerate when DoD publishes a new PKCS#7 bundle version.
"""


def _pems_from_pkcs7(path: str) -> list[str]:
    """Every certificate in a DER PKCS#7 file, root and subordinates alike."""
    result = subprocess.run(
        ["openssl", "pkcs7", "-inform", "DER", "-in", path,
         "-print_certs", "-outform", "PEM"],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode != 0:
        raise SystemExit(
            f"could not read {path}:\n{result.stderr.strip()}"
        )
    return certs.split_pem(result.stdout)


def build_bundle() -> tuple[str, list[str]]:
    """Rebuild the trust-anchor bundle. Returns (pem_text, source_paths_used).

    Fails loudly rather than emitting a partial bundle: a bundle that is one
    root short is a machine that cannot reach a CAC site, and it would fail
    later and somewhere else.
    """
    if not certs.openssl_available():
        raise SystemExit("openssl is required to rebuild the bundle")

    roots: list[str] = []
    problems: list[str] = []
    used: list[str] = []

    with tempfile.TemporaryDirectory() as workdir:
        for relative in SOURCES:
            path = os.path.join(ROOT, relative)
            if not os.path.exists(path):
                problems.append(f"missing source file: {relative}")
                continue
            used.append(relative)
            candidates = _pems_from_pkcs7(path)
            kept = 0
            for index, pem in enumerate(candidates):
                if certs.is_self_signed(pem, workdir, f"r{index}"):
                    roots.append(pem)
                    kept += 1
            if kept != 1:
                problems.append(
                    f"{os.path.basename(relative)}: expected exactly 1 self-signed "
                    f"root, found {kept} (of {len(candidates)} certificates)"
                )

    if problems:
        raise SystemExit(
            "refusing to build a bundle from these sources:\n  "
            + "\n  ".join(problems)
        )
    if not roots:
        raise SystemExit("no self-signed roots were found in the source files")

    # One certificate immediately after the next, no blank line between, which
    # is what the committed bundle does. `pem.rstrip()` then a single trailing
    # newline: a blank line here would make `--check` report a difference
    # between two byte-different files that hold identical certificates.
    body = "\n".join(pem.rstrip() for pem in roots)
    return f"{BUNDLE_HEADER}{body}\n", used


def report(pem_text: str) -> None:
    names, problems = certs.verify_roots_only(pem_text)
    print(f"Rebuilt bundle: {len(names)} root(s)")
    for name in names:
        print(f"  - {name}")
    if problems:
        print("\nPROBLEMS (this bundle must not be committed):")
        for problem in problems:
            print(f"  ! {problem}")
    else:
        print("\nAll self-signed and in date. Safe to install as trust anchors.")


SOURCE_DIGESTS = "DoD_Roots.sources.sha256"


def load_pinned_digests() -> dict:
    """The committed digest of every source file, as `<sha256>  <path>`.

    This is the trust anchor, not the CMS signature. See the header of the file
    itself for why: openssl cannot validate DoD's signature with a current build
    (SHA-1 in the legacy digest field, and the signer has since expired), yet it
    still writes the payload, so the digests can be read but not authenticated.
    Flipping one byte of a copied `.sha256` changes the digest list it yields and
    openssl returns the same exit code either way, so anything that trusts the
    payload alone trusts a file an attacker can edit.

    Pinned in git, a change to it is a reviewable commit rather than a silent
    edit. A checker that rejected on openssl's exit status instead would reject
    the genuine publication too, because that status is 4 for the real files.
    """
    path = os.path.join(ROOT, SOURCE_DIGESTS)
    digests = {}
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                digests[parts[1].strip()] = parts[0]
    return digests


def _cms_payload(signature: str) -> str:
    """Extract the digest list from a bundle's CMS manifest.

    Returns "" when nothing could be read. Never raises: an unreadable signature
    is a finding for the caller to report, not an exception on a maintenance
    path.
    """
    with tempfile.NamedTemporaryFile("r", suffix=".txt", delete=False) as fh:
        target = fh.name
    try:
        subprocess.run(
            ["openssl", "cms", "-verify", "-inform", "DER", "-in", signature,
             "-noverify", "-out", target],
            capture_output=True, text=True, timeout=60,
        )
        with open(target, encoding="utf-8", errors="replace") as out:
            return out.read()
    except OSError:
        return ""
    finally:
        try:
            os.unlink(target)
        except OSError:
            pass


def verify_sources() -> int:
    """Check every source file against the committed digests, then against DoD.

    Two independent checks, because neither is sufficient alone:

    1. Each file is hashed and compared to `DoD_Roots.sources.sha256`, which is
       in git. This is the check that can actually fail against a tampered file.
    2. The CMS payload in each bundle's `.sha256` is extracted and compared to
       the same list. DoD's signature cannot be validated by a current OpenSSL,
       so this is corroboration rather than proof -- but a payload that
       *disagrees* with the committed digests means someone edited one of the
       two, and that is a hard failure either way.

    Reporting the disagreement is the point. A checker that only looked at the
    CMS payload would happily accept a source bundle whose digests had been
    rewritten to match.
    """
    try:
        pinned = load_pinned_digests()
    except OSError as exc:
        print(f"  FAILED  cannot read {SOURCE_DIGESTS}: {exc}")
        return 1
    if not pinned:
        print(f"  FAILED  {SOURCE_DIGESTS} contains no digests")
        return 1

    failures = 0
    checked = mismatched = missing = 0
    disagreements = []

    for relative, want in sorted(pinned.items()):
        target = os.path.join(ROOT, relative)
        if not os.path.exists(target):
            print(f"  ! missing  {relative}")
            missing += 1
            continue
        with open(target, "rb") as blob:
            got = hashlib.sha256(blob.read()).hexdigest()
        if got == want:
            checked += 1
        else:
            mismatched += 1
            print(f"  ! altered  {relative}")
            print(f"            committed {want}")
            print(f"            on disk   {got}")

    # Cross-check DoD's own digest list against the committed one.
    directories = []
    for relative in SOURCES:
        directory = os.path.dirname(os.path.join(ROOT, relative))
        if directory not in directories:
            directories.append(directory)
    for directory in directories:
        label = os.path.basename(directory)
        signatures = [f for f in os.listdir(directory) if f.endswith(".sha256")]
        if not signatures:
            disagreements.append(f"{label}: no .sha256 manifest present")
            continue
        payload = _cms_payload(os.path.join(directory, signatures[0]))
        if not payload:
            disagreements.append(f"{label}: the signed manifest could not be read")
            continue
        for line in payload.replace("\r", "").splitlines():
            line = line.strip()
            if not line:
                continue
            parts = line.split(None, 1)
            if len(parts) != 2:
                continue
            signed_digest, name = parts[0], parts[1].strip()
            committed = pinned.get(os.path.join(label, name))
            if committed is None:
                continue          # a file we do not use; not our business
            if committed != signed_digest:
                disagreements.append(
                    f"{label}/{name}: DoD's manifest says {signed_digest[:16]}..., "
                    f"this repository pins {committed[:16]}..."
                )

    print(f"  {'OK' if not (mismatched or missing) else 'FAILED'}  "
          f"{checked}/{len(pinned)} file(s) match the committed digests"
          + (f", {mismatched} altered, {missing} missing"
             if (mismatched or missing) else ""))
    if disagreements:
        print("  FAILED  DoD's signed manifests disagree with this repository:")
        for line in disagreements:
            print(f"            - {line}")
    if mismatched or missing or disagreements:
        failures += 1

    return failures


DESCRIPTION = (
    "Rebuild DoD_Roots.pem from the signed source bundles in this repository, "
    "and prove the result. --check reports whether the committed files still "
    "match the sources; --write regenerates them; --verify-sources confirms the "
    "sources are unmodified from DoD's signed publication."
)


def write_source_digests() -> int:
    """Regenerate DoD_Roots.sources.sha256 from the bundles as they are now.

    Deliberately does not consult the CMS payload. The file being written is the
    independent record the payload is checked against, so seeding it from the
    payload would make the cross-check vacuous -- the two could never disagree,
    and the whole point would be lost.
    """
    import importlib
    header = importlib.import_module("sentinel_certs")

    # Only files DoD actually signed, and only ones this repository publishes.
    # The full-chain PEMs are deliberately not published -- they hold issuing CAs
    # and intermediates, and sit next to a trust-anchor bundle in a public
    # repository -- and pinning them here would quietly put them back.
    covered = set()
    for directory in sorted({
        os.path.dirname(os.path.join(ROOT, relative)) for relative in SOURCES
    }):
        label = os.path.basename(directory)
        signatures = [f for f in os.listdir(directory) if f.endswith(".sha256")]
        if not signatures:
            continue
        payload = _cms_payload(os.path.join(directory, signatures[0]))
        for line in payload.replace("\r", "").splitlines():
            parts = line.strip().split(None, 1)
            if len(parts) == 2:
                covered.add(os.path.join(label, parts[1].strip()))

    rows = []
    for relative in sorted(covered):
        path = os.path.join(ROOT, relative)
        if not os.path.isfile(path):
            continue
        with open(path, "rb") as blob:
            rows.append(f"{hashlib.sha256(blob.read()).hexdigest()}  {relative}")
    if not rows:
        print("  FAILED  no source files found")
        return 1

    path = os.path.join(ROOT, SOURCE_DIGESTS)
    existing_header = []
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                existing_header.append(line)
                if not line.startswith("#"):
                    break
    with open(path, "w", encoding="utf-8") as fh:
        fh.writelines(existing_header or [f"# Sentinel source digests.\n"])
        fh.write("\n".join(sorted(rows)) + "\n")
    print(f"  Wrote {len(rows)} digest(s) to {SOURCE_DIGESTS}.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="refresh_roots.py",
        description=DESCRIPTION,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--check", action="store_true",
        help="rebuild in memory and report whether the committed files match",
    )
    group.add_argument(
        "--write", action="store_true",
        help="rebuild and overwrite DoD_Roots.pem and the manifest",
    )
    group.add_argument(
        "--verify-sources", action="store_true",
        help="check the source bundles against the committed digests, and "
             "cross-check DoD's signed manifests against them",
    )
    group.add_argument(
        "--write-sources", action="store_true",
        help="regenerate DoD_Roots.sources.sha256 from the bundles as they are "
             "now; review the diff before committing",
    )
    args = parser.parse_args(argv)

    if args.write_sources:
        # Rewrites the trust anchor, so it prints loudly and refuses to pretend
        # this is routine. The point of the file is that a change to it is a
        # reviewable commit; regenerating it silently would remove that.
        print("Rewriting the committed source digests from the files as they are now.")
        print("This is the trust anchor for --verify-sources. Read the diff before")
        print("committing it, and confirm the sources really did change upstream.")
        print()
        return write_source_digests()

    if args.verify_sources:
        print("Checking source bundles against DoD's signed manifests:")
        print(f"  (upstream: {UPSTREAM})\n")
        failures = verify_sources()
        if failures:
            print(f"\n{failures} bundle(s) failed. Do not rebuild from these files.")
            return 1
        print("\nAll source files are unmodified from the signed publication.")
        return 0

    pem_text, used = build_bundle()
    report(pem_text)

    bundle_path = os.path.join(ROOT, BUNDLE_NAME)
    manifest_path = os.path.join(ROOT, MANIFEST_NAME)

    if args.write:
        with open(bundle_path, "w", encoding="utf-8") as fh:
            fh.write(pem_text)
        with open(manifest_path, "w", encoding="utf-8") as fh:
            fh.write(certs.render_manifest(pem_text))
        print(f"\nWrote {BUNDLE_NAME} and {MANIFEST_NAME} from {len(used)} source file(s).")
        print("Review the diff, then commit both files together.")
        return 0

    # --check
    with open(bundle_path, encoding="utf-8") as fh:
        committed = fh.read()
    if committed == pem_text:
        print(f"\n{BUNDLE_NAME} is up to date with the sources.")
    else:
        print(f"\n{BUNDLE_NAME} DIFFERS from the sources.")
        print("Run with --write to regenerate it.")
        return 1

    with open(manifest_path, encoding="utf-8") as fh:
        manifest_text = fh.read()
    differences = certs.compare_to_manifest(committed, manifest_text)
    if differences:
        print(f"{MANIFEST_NAME} does not describe {BUNDLE_NAME}:")
        for difference in differences:
            print(f"  ! {difference}")
        return 1
    print(f"{MANIFEST_NAME} matches {BUNDLE_NAME}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
