#!/usr/bin/env python3
"""Rebuild DoD_Roots.pem from the source bundles, and prove the result.

    ./tools/refresh_roots.py --check        is the committed bundle still right?
    ./tools/refresh_roots.py --write        rebuild it and the manifest
    ./tools/refresh_roots.py --verify-sources   check the sources are genuine

Why this exists
---------------
Sentinel ships a bundle of DoD trust anchors so that installing it never
requires the user to visit a website and download anything. That answers "how do
I get the certificates" but not the question that comes next: "how do I know
these are the current ones?"

Answering that offline needs two things this repository now carries: the signed
source bundles DoD publishes, and a manifest recording what the build produced.
This tool is the link between them.

    sources -> (self-signed filter) -> DoD_Roots.pem -> DoD_Roots.manifest

The filter is the security-relevant step. Each per-root `.p7b` from DoD contains
the root *and every certificate beneath it* -- 59 certificates in total across
the seven files -- so "take the first certificate" would install an issuing CA as
a root of trust, which is a materially larger trust surface than intended. Only
self-signed certificates are kept, and that is checked by verifying each
certificate's signature under its own public key rather than by comparing
subject and issuer strings.

`--verify-sources` checks the source files against the SHA-256 manifest that DoD
ships inside each bundle's `.sha256` file, which is a CMS object signed by a DoD
code-signing credential. That answers "are the files in this repository
unmodified?", which is a different and weaker question than "does the CMS
signature still validate?" -- see the note in `verify_sources`.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import sentinel_certs as certs  # noqa: E402

BUNDLE_NAME = "DoD_Roots.pem"
MANIFEST_NAME = certs.MANIFEST_NAME

# The source files, in the order the bundle is built. Order is part of the
# contract: the manifest records the bundle in this order, so changing it is a
# change to the release, not a cosmetic reordering.
#
# These are the per-root files rather than the combined ones on purpose. The
# combined `Certificates_PKCS7_v5.6_DoD.pem.p7b` carries DoD's own idea of which
# certificates belong, and this tool's job is to derive the roots independently
# and compare, not to take the publisher's word for which subset to trust.
SOURCES = (
    "certificates_pkcs7_v5_12_eca/certificates_pkcs7_v5_12_eca_ECA_Root_CA_4_der.p7b",
    "certificates_pkcs7_v5_12_eca/certificates_pkcs7_v5_12_eca_ECA_Root_CA_5_der.p7b",
    "Certificates_PKCS7_v5_17_WCF/Certificates_PKCS7_v5_17_WCF_DoD_WCF_Root_CA_1.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_5.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_4.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_3.der.p7b",
    "Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD_DoD_Root_CA_2.der.p7b",
)

# Where DoD publishes the bundles, for the record in the commit message. Not
# fetched by this tool: a build that silently pulled from the network would make
# the release unreproducible, which is the opposite of what a manifest is for.
UPSTREAM = "https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/"

# Reproduced byte-for-byte on every build so that `--check` is a meaningful
# comparison. The certificates themselves are what matter; this only has to stay
# stable, and a reformat that changes no certificate should not read as a change
# to the trust store.
BUNDLE_HEADER = """\
# DoD root certificates (self-signed trust anchors only).
# Generated by tools/refresh_roots.py -- do not edit by hand.
# Regenerate when DoD publishes a new PKCS#7 bundle version.
"""


def _pems_from_pkcs7(path: str) -> list[str]:
    """Every certificate in a DER PKCS#7 file, root and subordinates alike."""
    result = subprocess.run(
        ["openssl", "pkcs7", "-inform", "DER", "-in", path,
         "-print_certs", "-outform", "PEM"],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode != 0:
        raise SystemExit(
            f"could not read {path}:\n{result.stderr.strip()}"
        )
    return certs.split_pem(result.stdout)


def build_bundle() -> tuple[str, list[str]]:
    """Rebuild the trust-anchor bundle. Returns (pem_text, source_paths_used).

    Fails loudly rather than emitting a partial bundle: a bundle that is one
    root short is a machine that cannot reach a CAC site, and it would fail
    later and somewhere else.
    """
    if not certs.openssl_available():
        raise SystemExit("openssl is required to rebuild the bundle")

    roots: list[str] = []
    problems: list[str] = []
    used: list[str] = []

    with tempfile.TemporaryDirectory() as workdir:
        for relative in SOURCES:
            path = os.path.join(ROOT, relative)
            if not os.path.exists(path):
                problems.append(f"missing source file: {relative}")
                continue
            used.append(relative)
            candidates = _pems_from_pkcs7(path)
            kept = 0
            for index, pem in enumerate(candidates):
                if certs.is_self_signed(pem, workdir, f"r{index}"):
                    roots.append(pem)
                    kept += 1
            if kept != 1:
                problems.append(
                    f"{os.path.basename(relative)}: expected exactly 1 self-signed "
                    f"root, found {kept} (of {len(candidates)} certificates)"
                )

    if problems:
        raise SystemExit(
            "refusing to build a bundle from these sources:\n  "
            + "\n  ".join(problems)
        )
    if not roots:
        raise SystemExit("no self-signed roots were found in the source files")

    # One certificate immediately after the next, no blank line between, which
    # is what the committed bundle does. `pem.rstrip()` then a single trailing
    # newline: a blank line here would make `--check` report a difference
    # between two byte-different files that hold identical certificates.
    body = "\n".join(pem.rstrip() for pem in roots)
    return f"{BUNDLE_HEADER}{body}\n", used


def report(pem_text: str) -> None:
    names, problems = certs.verify_roots_only(pem_text)
    print(f"Rebuilt bundle: {len(names)} root(s)")
    for name in names:
        print(f"  - {name}")
    if problems:
        print("\nPROBLEMS (this bundle must not be committed):")
        for problem in problems:
            print(f"  ! {problem}")
    else:
        print("\nAll self-signed and in date. Safe to install as trust anchors.")


def verify_sources() -> int:
    """Check the source files against the SHA-256 manifest DoD ships with them.

    Each bundle contains a `<bundle>.sha256` file which is not a checksum list
    despite the name: it is a CMS SignedData object whose payload is a list of
    SHA-256 digests, signed by a DoD PKE code-signing credential. The payload is
    extracted and every listed file compared.

    What this does *not* do is re-validate the CMS signature, and the reason is
    worth stating rather than hiding: the signature chains to DoD Root CA 3, but
    the signing certificate has since expired, so a present-day OpenSSL refuses
    it. That is a statement about the age of the publication, not about its
    integrity -- a signature made while the certificate was valid remains a
    record of what was signed. The digests below are therefore trustworthy as a
    record of the published contents, and this function confirms the files in
    this repository still match that record exactly.
    """
    failures = 0
    # One pass per source directory, not per source file: every per-root .p7b
    # lives in the same bundle as its signed manifest, so iterating the file list
    # would verify the same manifest seven times and print seven identical lines.
    directories = []
    for relative in SOURCES:
        directory = os.path.dirname(os.path.join(ROOT, relative))
        if directory not in directories:
            directories.append(directory)

    for directory in directories:
        label = os.path.basename(directory)
        if not os.path.isdir(directory):
            print(f"  FAILED  {label}: the source directory is missing")
            failures += 1
            continue
        signatures = [f for f in os.listdir(directory) if f.endswith(".sha256")]
        if not signatures:
            print(f"  FAILED  {label}: no .sha256 manifest present")
            failures += 1
            continue

        signature = os.path.join(directory, signatures[0])
        # The signature itself will not validate (the signing certificate has
        # since expired), but the payload still extracts, so read it to a
        # temporary file either way. The first call below is kept only to make
        # the expected failure visible to anyone running this by hand.
        probe = subprocess.run(
            ["openssl", "cms", "-verify", "-inform", "DER", "-in", signature,
             "-noverify", "-out", os.devnull],
            capture_output=True, text=True, timeout=60,
        )
        with tempfile.NamedTemporaryFile("r+", suffix=".txt", delete=False) as fh:
            manifest_path = fh.name
        subprocess.run(
            ["openssl", "cms", "-verify", "-inform", "DER", "-in", signature,
             "-noverify", "-out", manifest_path],
            capture_output=True, text=True, timeout=60,
        )
        if probe.returncode != 0 and not os.path.getsize(manifest_path):
            print(f"  FAILED  {label}: could not read the signed manifest at all, "
                  "so nothing here is verified")
            os.unlink(manifest_path)
            failures += 1
            continue

        checked = mismatched = missing = 0
        with open(manifest_path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.replace("\r", "").strip()
                if not line:
                    continue
                parts = line.split(None, 1)
                if len(parts) != 2:
                    continue
                want, name = parts[0], parts[1].strip()
                target = os.path.join(directory, name)
                if not os.path.exists(target):
                    missing += 1
                    continue
                with open(target, "rb") as blob:
                    got = hashlib.sha256(blob.read()).hexdigest()
                if got == want:
                    checked += 1
                else:
                    mismatched += 1
                    print(f"  ! {name} does not match the signed digest")
        os.unlink(manifest_path)

        status = "OK" if not (mismatched or missing) else "FAILED"
        print(f"  {status}  {label}: "
              f"{checked} file(s) match DoD's signed manifest"
              + (f", {mismatched} mismatched, {missing} missing" if (mismatched or missing) else ""))
        if mismatched or missing:
            failures += 1

    return failures


DESCRIPTION = (
    "Rebuild DoD_Roots.pem from the signed source bundles in this repository, "
    "and prove the result. --check reports whether the committed files still "
    "match the sources; --write regenerates them; --verify-sources confirms the "
    "sources are unmodified from DoD's signed publication."
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="refresh_roots.py",
        description=DESCRIPTION,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--check", action="store_true",
        help="rebuild in memory and report whether the committed files match",
    )
    group.add_argument(
        "--write", action="store_true",
        help="rebuild and overwrite DoD_Roots.pem and the manifest",
    )
    group.add_argument(
        "--verify-sources", action="store_true",
        help="check the source bundles against DoD's signed SHA-256 manifests",
    )
    args = parser.parse_args(argv)

    if args.verify_sources:
        print("Checking source bundles against DoD's signed manifests:")
        print(f"  (upstream: {UPSTREAM})\n")
        failures = verify_sources()
        if failures:
            print(f"\n{failures} bundle(s) failed. Do not rebuild from these files.")
            return 1
        print("\nAll source files are unmodified from the signed publication.")
        return 0

    pem_text, used = build_bundle()
    report(pem_text)

    bundle_path = os.path.join(ROOT, BUNDLE_NAME)
    manifest_path = os.path.join(ROOT, MANIFEST_NAME)

    if args.write:
        with open(bundle_path, "w", encoding="utf-8") as fh:
            fh.write(pem_text)
        with open(manifest_path, "w", encoding="utf-8") as fh:
            fh.write(certs.render_manifest(pem_text))
        print(f"\nWrote {BUNDLE_NAME} and {MANIFEST_NAME} from {len(used)} source file(s).")
        print("Review the diff, then commit both files together.")
        return 0

    # --check
    with open(bundle_path, encoding="utf-8") as fh:
        committed = fh.read()
    if committed == pem_text:
        print(f"\n{BUNDLE_NAME} is up to date with the sources.")
    else:
        print(f"\n{BUNDLE_NAME} DIFFERS from the sources.")
        print("Run with --write to regenerate it.")
        return 1

    with open(manifest_path, encoding="utf-8") as fh:
        manifest_text = fh.read()
    differences = certs.compare_to_manifest(committed, manifest_text)
    if differences:
        print(f"{MANIFEST_NAME} does not describe {BUNDLE_NAME}:")
        for difference in differences:
            print(f"  ! {difference}")
        return 1
    print(f"{MANIFEST_NAME} matches {BUNDLE_NAME}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
